### ISSUE TITLE
Flexbox & CSS

### ISSUE THREAD

**Issue by ghost** [mattjudd/teaCozy#5]
https://github.com/mattjudd/teaCozy/blob/master/resources/css/styles.css#L16-L27

Excellent job using `flexbox` to implement your layout. 

You've also made your CSS quite simple to read by adhering to style conventions, listing your styles logically, and writing it very efficiently with minimal repetition. Nicely done. 

Consider leaving comments to help document your implementation as your websites grow more complex 👍

**Comment by mattjudd** [comment]
I'm loving `flexbox`. That has been a big gain for me from this course. I'm big with comments usually.
